# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-21 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import spese.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'account',
                'ordering': ['name'],
                'verbose_name_plural': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='amount')),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='spese.Account')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'expense',
                'ordering': ['-date', 'account'],
                'verbose_name_plural': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='PercentDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(validators=[spese.models.valid_percent], verbose_name='percent')),
                ('valid_from', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='valid from')),
                ('valid_to', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='valid to')),
            ],
            options={
                'verbose_name': 'percent deduction',
                'ordering': ['work_cost_type__name', '-valid_from'],
                'verbose_name_plural': 'percent deductions',
            },
        ),
        migrations.CreateModel(
            name='WCType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'expense work cost type',
                'ordering': ['name'],
                'verbose_name_plural': 'expense work cost types',
            },
        ),
        migrations.AddField(
            model_name='percentdeduction',
            name='wc_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wc_ype', to='spese.WCType'),
        ),
        migrations.AddField(
            model_name='expense',
            name='work_cost_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_cost_type', to='spese.WCType'),
        ),
    ]
