# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'channel',
                'verbose_name_plural': 'channels',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AlterUniqueTogether(
            name='hiddencategory',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='hiddencategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='hiddencategory',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', 'channel'], 'verbose_name': 'expense', 'verbose_name_plural': 'expenses'},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='HiddenCategory',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='expense',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='spese.Channel'),
        ),
    ]
