# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-26 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'transfer funds',
                'verbose_name': 'transfer fund',
            },
        ),
        migrations.AlterModelOptions(
            name='percentdeduction',
            options={'ordering': ['wc_type__name', '-valid_from'], 'verbose_name': 'percent deduction', 'verbose_name_plural': 'percent deductions'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='work_cost_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_cost_type', to='spese.WCType'),
        ),
        migrations.AddField(
            model_name='transferfund',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='spese.Expense'),
        ),
        migrations.AddField(
            model_name='transferfund',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='spese.Expense'),
        ),
    ]
