# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0003_auto_20160728_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channel',
            new_name='Source',
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', 'source'], 'verbose_name': 'expense', 'verbose_name_plural': 'expenses'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['name'], 'verbose_name': 'source', 'verbose_name_plural': 'sources'},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='channel',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
