# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0004_auto_20160807_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='source',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='spese.Source'),
        ),
    ]
