# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 14:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spese', '0005_auto_20160807_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
