# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-07 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spese', '0007_auto_20160913_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Source',
            new_name='Account',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name'], 'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', 'account'], 'verbose_name': 'expense', 'verbose_name_plural': 'expenses'},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='source',
            new_name='account',
        ),
    ]
