# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-21 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spese', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.PositiveIntegerField(verbose_name='km')),
                ('unit_cost', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='unit_cost')),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spese.Expense')),
            ],
            options={
                'verbose_name_plural': 'events',
                'verbose_name': 'event',
                'ordering': ['expense'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('start', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='start')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end')),
            ],
            options={
                'verbose_name_plural': 'vehicles',
                'verbose_name': 'vehicle',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'VEvents',
                'verbose_name': 'vehicle event',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'VTypes',
                'verbose_name': 'vehicle type',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veicoli.VType'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veicoli.Vehicle'),
        ),
        migrations.AddField(
            model_name='event',
            name='vevent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veicoli.VEvent'),
        ),
    ]
