# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veicoli', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vevent',
            options={'ordering': ['name'], 'verbose_name': 'vehicle event', 'verbose_name_plural': 'VEvents'},
        ),
        migrations.AlterModelOptions(
            name='vtype',
            options={'ordering': ['name'], 'verbose_name': 'vehicle type', 'verbose_name_plural': 'VTypes'},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='vevent',
        ),
    ]
